-- ============================================================
--  Схемы: sales, production (аналог SalesLT, Production)
-- ============================================================

-- В PostgreSQL имя схемы по умолчанию = имя пользователя,
-- поэтому пути к объектам задаем явно: sales.customer и т.д.
DROP SCHEMA IF EXISTS sales CASCADE;
DROP SCHEMA IF EXISTS production CASCADE;
CREATE SCHEMA sales;
CREATE SCHEMA production;

-- ---------- Справочники каталога ----------
CREATE TABLE production.productcategory (
    productcategoryid   integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(50) NOT NULL UNIQUE
);

CREATE TABLE production.productmodel (
    productmodelid      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(50) NOT NULL UNIQUE,
    catalogdescription  text
);

-- ---------- Товары ----------
CREATE TABLE production.product (
    productid           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                varchar(100) NOT NULL,
    productnumber       varchar(25) NOT NULL UNIQUE,
    color               varchar(15),
    standardcost        numeric(19,4) NOT NULL DEFAULT 0 CHECK (standardcost >= 0),
    listprice           numeric(19,4) NOT NULL DEFAULT 0 CHECK (listprice >= 0),
    sellstartdate       date NOT NULL,
    sellenddate         date,
    productcategoryid   integer REFERENCES production.productcategory,
    productmodelid      integer REFERENCES production.productmodel,
    rowguid             uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate        timestamp NOT NULL DEFAULT now()
);

-- ---------- Клиенты ----------
CREATE TABLE sales.customer (
    customerid          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namestyle           boolean NOT NULL DEFAULT false,
    firstname           varchar(50) NOT NULL,
    lastname            varchar(50) NOT NULL,
    companyname         varchar(128),
    emailaddress        varchar(256),
    phone               varchar(25),
    rowguid             uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate        timestamp NOT NULL DEFAULT now()
);

-- ---------- Адреса и связь многие-ко-многим ----------
CREATE TABLE sales.address (
    addressid           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    addressline1        varchar(60) NOT NULL,
    addressline2        varchar(60),
    city                varchar(30) NOT NULL,
    stateprovince       varchar(50) NOT NULL,
    countryregion       varchar(50) NOT NULL,
    postalcode          varchar(15) NOT NULL,
    rowguid             uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate        timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sales.customeraddress (
    customerid          integer NOT NULL REFERENCES sales.customer,
    addressid           integer NOT NULL REFERENCES sales.address,
    addresstype         varchar(50) NOT NULL,
    rowguid             uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate        timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (customerid, addressid, addresstype),
    CONSTRAINT ck_addresstype CHECK (addresstype IN ('Main Office', 'Shipping'))
);

-- ---------- Заказы ----------
CREATE TABLE sales.salesorderheader (
    salesorderid        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orderdate           timestamp NOT NULL DEFAULT now(),
    duedate             timestamp,
    status              smallint NOT NULL DEFAULT 1,
    customerid          integer NOT NULL REFERENCES sales.customer,
    subtotal            numeric(12,2) NOT NULL DEFAULT 0,
    taxamt              numeric(12,2) NOT NULL DEFAULT 0,
    freight             numeric(12,2) NOT NULL DEFAULT 0,
    totaldue            numeric(12,2) NOT NULL DEFAULT 0,
    comment             text,
    rowguid             uuid NOT NULL DEFAULT gen_random_uuid(),
    modifieddate        timestamp NOT NULL DEFAULT now()
);

CREATE TABLE sales.salesorderdetail (
    salesorderdetailid  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salesorderid        integer NOT NULL REFERENCES sales.salesorderheader,
    productid           integer NOT NULL REFERENCES production.product,
    orderqty            integer NOT NULL CHECK (orderqty > 0),
    unitprice           numeric(12,2) NOT NULL CHECK (unitprice >= 0),
    linetotal           numeric(12,2) NOT NULL DEFAULT 0
);

-- ---------- Сотрудники ----------
CREATE TABLE sales.employee (
    employeeid          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname           varchar(50) NOT NULL,
    lastname            varchar(50) NOT NULL,
    city                varchar(30),
    stateprovince       varchar(50),
    countryregion       varchar(50)
);

-- ---------- Индексы (как в оригинале AdventureWorksLT) ----------
CREATE INDEX idx_product_category ON production.product (productcategoryid);
CREATE INDEX idx_product_model    ON production.product (productmodelid);
CREATE INDEX idx_soh_customer     ON sales.salesorderheader (customerid);
CREATE INDEX idx_sod_order        ON sales.salesorderdetail (salesorderid);
CREATE INDEX idx_sod_product      ON sales.salesorderdetail (productid);
CREATE INDEX idx_ca_customer      ON sales.customeraddress (customerid);
CREATE INDEX idx_ca_address       ON sales.customeraddress (addressid);

-- ---------- Представления (аналог SalesLT.vGetAllCategories и т.п.) ----------
CREATE VIEW sales.vproductanddescription AS
SELECT p.productid,
       pc.name AS category,
       p.name  AS productname,
       p.listprice
FROM production.product p
LEFT JOIN production.productcategory pc
       ON p.productcategoryid = pc.productcategoryid;

CREATE VIEW sales.vcustomeraddresses AS
SELECT c.customerid,
       c.companyname,
       a.addressid,
       a.addressline1,
       a.city,
       a.stateprovince,
       a.countryregion,
       ca.addresstype
FROM sales.customer c
JOIN sales.customeraddress ca ON c.customerid = ca.customerid
JOIN sales.address a          ON ca.addressid = a.addressid;
